apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-scan-binding
subjects:
- kind: User
  name: dso-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: trivy-scan 
  apiGroup: rbac.authorization.k8s.io
