name: Site scanner

on:
  workflow_dispatch:


jobs:
  DAST-scan:
    name: DAST site scanner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster_ip_secret_key: [CLUSTER_IP]
        port: [31546,31547]

    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: http://${{ secrets[matrix.cluster_ip_secret_key] }}:${{ matrix.port}}
          artifact_name: zap_scan_${{ secrets[matrix.cluster_ip_secret_key] }}_${{ matrix.port }}
